[package]
name = "ravenman"
version = "0.1.0"
authors = ["Shervin"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.11.3"
# gdnative = { path = "../../godot-rust/gdnative" }
